import type { Country } from "./types";

/**
 * The World Clock country catalog — the single source of truth for every
 * country profile the app shows.
 *
 * This is bundled data, not a fetch. Capitals, currencies, languages, dialling
 * codes and what a place is known for barely change from year to year, and
 * bundling them means the clocks, the country details and the specialities all
 * work with no connection at all. Headlines are the only part of the app that
 * needs the network.
 *
 * `population` and `area` are approximate reference figures — see
 * {@link POPULATION_YEAR}, which the UI cites next to them so the numbers are
 * never mistaken for live statistics.
 */

/** The year the bundled population estimates are anchored to. */
export const POPULATION_YEAR = 2024;

export const COUNTRIES: Country[] = [
  /* ------------------------------- Asia -------------------------------- */
  {
    code: "IN",
    name: "India",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
    currency: "Indian rupee",
    currencyCode: "INR",
    currencySymbol: "₹",
    languages: ["Hindi", "English", "Bengali", "Telugu", "Marathi", "Tamil"],
    dialCode: "+91",
    population: 1_441_000_000,
    area: 3_287_263,
    driving: "left",
    tld: ".in",
    newsQuery: "hl=en-IN&gl=IN&ceid=IN:en",
    about:
      "The world's most populous country and its largest democracy, stretching from the Himalaya to the tropics across 28 states and eight union territories. It runs on a single half-hour-offset time zone, IST, despite spanning roughly 30 degrees of longitude.",
    known: [
      "Taj Mahal",
      "Ayurveda & yoga",
      "Spices and regional cuisines",
      "Bollywood",
      "IT and software services",
      "Cricket",
    ],
  },
  {
    code: "JP",
    name: "Japan",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    currency: "Japanese yen",
    currencyCode: "JPY",
    currencySymbol: "¥",
    languages: ["Japanese"],
    dialCode: "+81",
    population: 123_800_000,
    area: 377_975,
    driving: "left",
    tld: ".jp",
    about:
      "An archipelago of some 14,000 islands off the Pacific coast of Asia, where dense, meticulously engineered cities sit against mountains and forest. Greater Tokyo is the largest metropolitan area on Earth.",
    known: [
      "Shinkansen bullet trains",
      "Sushi and washoku cuisine",
      "Anime and manga",
      "Cherry blossom season",
      "Mount Fuji",
      "Robotics and electronics",
    ],
  },
  {
    code: "CN",
    name: "China",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
    currency: "Renminbi (yuan)",
    currencyCode: "CNY",
    currencySymbol: "¥",
    languages: ["Mandarin Chinese"],
    dialCode: "+86",
    population: 1_425_000_000,
    area: 9_596_961,
    driving: "right",
    tld: ".cn",
    about:
      "The world's second most populous country and its largest manufacturer, spanning deserts, the Tibetan plateau and a dense eastern seaboard. The whole country officially keeps a single time zone, Beijing time.",
    known: [
      "Great Wall",
      "Terracotta Army",
      "Tea culture",
      "Manufacturing and exports",
      "High-speed rail network",
      "Giant pandas",
    ],
  },
  {
    code: "KR",
    name: "South Korea",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    currency: "South Korean won",
    currencyCode: "KRW",
    currencySymbol: "₩",
    languages: ["Korean"],
    dialCode: "+82",
    population: 51_700_000,
    area: 100_210,
    driving: "right",
    tld: ".kr",
    about:
      "A mountainous peninsula nation that went from post-war reconstruction to a high-tech export economy within a generation. Roughly half the population lives in the Seoul capital area.",
    known: [
      "K-pop and Korean drama",
      "Samsung, Hyundai, LG",
      "Kimchi and Korean BBQ",
      "World-leading broadband",
      "Hangul alphabet",
      "Esports",
    ],
  },
  {
    code: "SG",
    name: "Singapore",
    capital: "Singapore",
    region: "Asia",
    subregion: "South-Eastern Asia",
    currency: "Singapore dollar",
    currencyCode: "SGD",
    currencySymbol: "S$",
    languages: ["English", "Malay", "Mandarin Chinese", "Tamil"],
    dialCode: "+65",
    population: 5_900_000,
    area: 735,
    driving: "left",
    tld: ".sg",
    about:
      "A city-state at the tip of the Malay Peninsula and one of the world's busiest ports and financial centres. Four official languages sit side by side in a country smaller than most capital cities.",
    known: [
      "Changi Airport",
      "Marina Bay Sands",
      "Hawker centre food",
      "Global finance and shipping",
      "Gardens by the Bay",
      "Strict cleanliness laws",
    ],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    region: "Asia",
    subregion: "Western Asia",
    currency: "UAE dirham",
    currencyCode: "AED",
    currencySymbol: "د.إ",
    languages: ["Arabic", "English"],
    dialCode: "+971",
    population: 9_500_000,
    area: 83_600,
    driving: "right",
    tld: ".ae",
    about:
      "A federation of seven emirates on the Arabian Gulf that turned oil revenue into trade, aviation and tourism hubs. An overwhelming majority of residents are expatriates.",
    known: [
      "Burj Khalifa",
      "Dubai shopping and tourism",
      "Emirates and Etihad airlines",
      "Desert and oasis landscapes",
      "Oil and gas",
      "Gold souks",
    ],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
    currency: "Saudi riyal",
    currencyCode: "SAR",
    currencySymbol: "﷼",
    languages: ["Arabic"],
    dialCode: "+966",
    population: 36_900_000,
    area: 2_149_690,
    driving: "right",
    tld: ".sa",
    about:
      "The largest country in the Middle East, covering most of the Arabian Peninsula and much of the Rub' al Khali desert. It holds Islam's two holiest cities and some of the world's largest petroleum reserves.",
    known: [
      "Mecca and Medina",
      "Hajj pilgrimage",
      "Petroleum reserves",
      "Rub' al Khali desert",
      "AlUla and Hegra",
      "Dates and Arabic coffee",
    ],
  },
  {
    code: "QA",
    name: "Qatar",
    capital: "Doha",
    region: "Asia",
    subregion: "Western Asia",
    currency: "Qatari riyal",
    currencyCode: "QAR",
    currencySymbol: "﷼",
    languages: ["Arabic", "English"],
    dialCode: "+974",
    population: 3_000_000,
    area: 11_586,
    driving: "right",
    tld: ".qa",
    about:
      "A small peninsula on the Arabian Gulf with among the world's largest natural gas reserves and highest income per head. It hosted the 2022 FIFA World Cup.",
    known: [
      "Liquefied natural gas",
      "Al Jazeera",
      "2022 FIFA World Cup",
      "Museum of Islamic Art",
      "Souq Waqif",
      "Falconry",
    ],
  },
  {
    code: "TH",
    name: "Thailand",
    capital: "Bangkok",
    region: "Asia",
    subregion: "South-Eastern Asia",
    currency: "Thai baht",
    currencyCode: "THB",
    currencySymbol: "฿",
    languages: ["Thai"],
    dialCode: "+66",
    population: 71_700_000,
    area: 513_120,
    driving: "left",
    tld: ".th",
    about:
      "A constitutional monarchy in mainland Southeast Asia, the only country in the region never colonised by a European power. Tourism and agriculture sit alongside a large manufacturing base.",
    known: [
      "Thai cuisine",
      "Buddhist temples",
      "Beaches and islands",
      "Muay Thai",
      "Floating markets",
      "Songkran festival",
    ],
  },
  {
    code: "ID",
    name: "Indonesia",
    capital: "Jakarta",
    region: "Asia",
    subregion: "South-Eastern Asia",
    currency: "Indonesian rupiah",
    currencyCode: "IDR",
    currencySymbol: "Rp",
    languages: ["Indonesian", "Javanese", "Sundanese"],
    dialCode: "+62",
    population: 279_000_000,
    area: 1_904_569,
    driving: "left",
    tld: ".id",
    about:
      "The world's largest archipelagic state — more than 17,000 islands spread across three time zones — and the country with the largest Muslim population. It sits squarely on the Pacific Ring of Fire.",
    known: [
      "Bali",
      "Borobudur temple",
      "Batik textiles",
      "Volcanoes and rainforest",
      "Komodo dragons",
      "Coffee and spices",
    ],
  },
  {
    code: "MY",
    name: "Malaysia",
    capital: "Kuala Lumpur",
    region: "Asia",
    subregion: "South-Eastern Asia",
    currency: "Malaysian ringgit",
    currencyCode: "MYR",
    currencySymbol: "RM",
    languages: ["Malay", "English", "Mandarin Chinese", "Tamil"],
    dialCode: "+60",
    population: 34_300_000,
    area: 330_803,
    driving: "left",
    tld: ".my",
    about:
      "Split between the Malay Peninsula and northern Borneo, with Malay, Chinese and Indian communities shaping a notably plural culture. Rainforest covers a large share of the land.",
    known: [
      "Petronas Twin Towers",
      "Nasi lemak and street food",
      "Borneo rainforest",
      "Palm oil and electronics",
      "Orangutans",
      "Langkawi and Penang",
    ],
  },
  {
    code: "VN",
    name: "Vietnam",
    capital: "Hanoi",
    region: "Asia",
    subregion: "South-Eastern Asia",
    currency: "Vietnamese dong",
    currencyCode: "VND",
    currencySymbol: "₫",
    languages: ["Vietnamese"],
    dialCode: "+84",
    population: 100_300_000,
    area: 331_212,
    driving: "right",
    tld: ".vn",
    about:
      "A long, narrow country along the eastern edge of the Indochinese Peninsula, from the Red River delta in the north to the Mekong delta in the south. It has become one of Asia's fastest-growing manufacturing economies.",
    known: [
      "Ha Long Bay",
      "Phở and bánh mì",
      "Vietnamese coffee",
      "Rice terraces",
      "Hội An old town",
      "Textiles and electronics",
    ],
  },
  {
    code: "PH",
    name: "Philippines",
    capital: "Manila",
    region: "Asia",
    subregion: "South-Eastern Asia",
    currency: "Philippine peso",
    currencyCode: "PHP",
    currencySymbol: "₱",
    languages: ["Filipino", "English"],
    dialCode: "+63",
    population: 118_000_000,
    area: 300_000,
    driving: "right",
    tld: ".ph",
    about:
      "An archipelago of more than 7,600 islands in the western Pacific, with Spanish and American history layered over Austronesian roots. English is an official language and widely used in business.",
    known: [
      "Island beaches and diving",
      "Banaue rice terraces",
      "Jeepneys",
      "Adobo and lechon",
      "Business process outsourcing",
      "Basketball",
    ],
  },
  {
    code: "PK",
    name: "Pakistan",
    capital: "Islamabad",
    region: "Asia",
    subregion: "Southern Asia",
    currency: "Pakistani rupee",
    currencyCode: "PKR",
    currencySymbol: "₨",
    languages: ["Urdu", "English", "Punjabi", "Sindhi", "Pashto"],
    dialCode: "+92",
    population: 245_000_000,
    area: 881_913,
    driving: "left",
    tld: ".pk",
    about:
      "A South Asian country running from the Arabian Sea to the Karakoram, home to five of the world's fourteen peaks above 8,000 metres. The Indus valley within it hosted one of the earliest urban civilisations.",
    known: [
      "K2 and the Karakoram",
      "Indus Valley sites",
      "Mughal architecture in Lahore",
      "Textiles and cotton",
      "Biryani and kebabs",
      "Cricket",
    ],
  },
  {
    code: "BD",
    name: "Bangladesh",
    capital: "Dhaka",
    region: "Asia",
    subregion: "Southern Asia",
    currency: "Bangladeshi taka",
    currencyCode: "BDT",
    currencySymbol: "৳",
    languages: ["Bengali"],
    dialCode: "+880",
    population: 174_000_000,
    area: 148_460,
    driving: "left",
    tld: ".bd",
    about:
      "Built almost entirely on the Ganges–Brahmaputra delta, one of the most densely populated countries on Earth. Its ready-made garment industry is among the world's largest.",
    known: [
      "Sundarbans mangroves",
      "Ready-made garments",
      "Bengali literature",
      "Cox's Bazar beach",
      "Jute production",
      "Microfinance",
    ],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    region: "Asia",
    subregion: "Southern Asia",
    currency: "Sri Lankan rupee",
    currencyCode: "LKR",
    currencySymbol: "රු",
    languages: ["Sinhala", "Tamil", "English"],
    dialCode: "+94",
    population: 22_000_000,
    area: 65_610,
    driving: "left",
    tld: ".lk",
    about:
      "An island south of India with a central highland core ringed by coastal plains and beaches. Colombo is the commercial capital; the legislative capital is neighbouring Sri Jayawardenepura Kotte.",
    known: [
      "Ceylon tea",
      "Sigiriya rock fortress",
      "Ancient Buddhist sites",
      "Cinnamon and spices",
      "Wildlife safaris",
      "Gemstones",
    ],
  },
  {
    code: "NP",
    name: "Nepal",
    capital: "Kathmandu",
    region: "Asia",
    subregion: "Southern Asia",
    currency: "Nepalese rupee",
    currencyCode: "NPR",
    currencySymbol: "रू",
    languages: ["Nepali"],
    dialCode: "+977",
    population: 30_900_000,
    area: 147_181,
    driving: "left",
    tld: ".np",
    about:
      "A landlocked Himalayan country holding eight of the world's ten highest mountains, including Everest. It keeps an unusual UTC+05:45 time zone, offset by 45 minutes.",
    known: [
      "Mount Everest",
      "Trekking and mountaineering",
      "Kathmandu valley temples",
      "Birthplace of the Buddha (Lumbini)",
      "Gurkha regiments",
      "Momo dumplings",
    ],
  },
  {
    code: "IL",
    name: "Israel",
    capital: "Jerusalem",
    region: "Asia",
    subregion: "Western Asia",
    currency: "Israeli new shekel",
    currencyCode: "ILS",
    currencySymbol: "₪",
    languages: ["Hebrew", "Arabic", "English"],
    dialCode: "+972",
    population: 9_800_000,
    area: 22_072,
    driving: "right",
    tld: ".il",
    about:
      "A small eastern-Mediterranean country running from the Negev desert to the Galilee hills, containing sites central to Judaism, Christianity and Islam. Tel Aviv is its commercial and technology centre.",
    known: [
      "Jerusalem old city",
      "Dead Sea",
      "Technology start-ups",
      "Desert agriculture",
      "Hummus and falafel",
      "Kibbutz movement",
    ],
  },
  {
    code: "TR",
    name: "Türkiye",
    capital: "Ankara",
    region: "Asia",
    subregion: "Western Asia",
    currency: "Turkish lira",
    currencyCode: "TRY",
    currencySymbol: "₺",
    languages: ["Turkish"],
    dialCode: "+90",
    population: 85_800_000,
    area: 783_562,
    driving: "right",
    tld: ".tr",
    // English coverage still overwhelmingly files under the exonym.
    newsSearch: "Turkey",
    about:
      "Straddling south-eastern Europe and western Asia across the Bosphorus, with Anatolia forming most of its landmass. Istanbul, its largest city, sits on both continents.",
    known: [
      "Hagia Sophia",
      "Cappadocia",
      "Turkish delight and baklava",
      "Turkish coffee and tea",
      "Carpets and kilims",
      "Ephesus and Pamukkale",
    ],
  },
  {
    code: "HK",
    name: "Hong Kong",
    capital: "Hong Kong",
    region: "Asia",
    subregion: "Eastern Asia",
    currency: "Hong Kong dollar",
    currencyCode: "HKD",
    currencySymbol: "HK$",
    languages: ["Cantonese", "English", "Mandarin Chinese"],
    dialCode: "+852",
    population: 7_500_000,
    area: 1_110,
    driving: "left",
    tld: ".hk",
    about:
      "A special administrative region of China on the Pearl River delta, and one of the world's densest cities and largest financial centres. Steep terrain pushes it upward — it has more skyscrapers than anywhere else.",
    known: [
      "Victoria Harbour skyline",
      "Global finance",
      "Dim sum",
      "Star Ferry and trams",
      "Peak Tram",
      "Hong Kong cinema",
    ],
  },
  {
    code: "MV",
    name: "Maldives",
    capital: "Malé",
    region: "Asia",
    subregion: "Southern Asia",
    currency: "Maldivian rufiyaa",
    currencyCode: "MVR",
    currencySymbol: "Rf",
    languages: ["Dhivehi", "English"],
    dialCode: "+960",
    population: 520_000,
    area: 300,
    driving: "left",
    tld: ".mv",
    about:
      "A chain of 26 coral atolls in the Indian Ocean and the world's lowest-lying country, averaging around 1.5 metres above sea level. Tourism and fishing carry the economy.",
    known: [
      "Overwater resorts",
      "Coral reefs and diving",
      "Atoll geography",
      "Tuna fishing",
      "Climate-change advocacy",
      "White-sand beaches",
    ],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    capital: "Astana",
    region: "Asia",
    subregion: "Central Asia",
    currency: "Kazakhstani tenge",
    currencyCode: "KZT",
    currencySymbol: "₸",
    languages: ["Kazakh", "Russian"],
    dialCode: "+7",
    population: 20_000_000,
    area: 2_724_900,
    driving: "right",
    tld: ".kz",
    about:
      "The world's largest landlocked country, mostly open steppe stretching from the Caspian Sea to the Altai mountains. It holds substantial oil, gas and uranium reserves.",
    known: [
      "Baikonur Cosmodrome",
      "Steppe landscapes",
      "Oil, gas and uranium",
      "Silk Road heritage",
      "Eagle hunting",
      "Astana's modern architecture",
    ],
  },

  /* ------------------------------ Europe ------------------------------- */
  {
    code: "GB",
    name: "United Kingdom",
    capital: "London",
    region: "Europe",
    subregion: "Northern Europe",
    currency: "Pound sterling",
    currencyCode: "GBP",
    currencySymbol: "£",
    languages: ["English"],
    dialCode: "+44",
    population: 68_400_000,
    area: 243_610,
    driving: "left",
    tld: ".uk",
    about:
      "Four nations — England, Scotland, Wales and Northern Ireland — in a union off the north-west coast of Europe. Greenwich, in London, gives its name to the reference meridian the world's time zones are measured from.",
    known: [
      "Greenwich Mean Time",
      "Royal family",
      "Premier League football",
      "The Beatles and British rock",
      "Shakespeare",
      "Tea culture",
    ],
  },
  {
    code: "IE",
    name: "Ireland",
    capital: "Dublin",
    region: "Europe",
    subregion: "Northern Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["English", "Irish"],
    dialCode: "+353",
    population: 5_300_000,
    area: 70_273,
    driving: "left",
    tld: ".ie",
    about:
      "An Atlantic island nation known for green, rain-fed landscapes and a literary tradition far out of proportion to its size. Dublin hosts the European headquarters of many large technology firms.",
    known: [
      "Cliffs of Moher",
      "Guinness and pub culture",
      "Irish literature",
      "St Patrick's Day",
      "Traditional music",
      "Tech European HQs",
    ],
  },
  {
    code: "FR",
    name: "France",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["French"],
    dialCode: "+33",
    population: 68_400_000,
    area: 551_695,
    driving: "right",
    tld: ".fr",
    about:
      "Reaching from the Atlantic to the Alps and the Mediterranean, with overseas territories that give it a presence in every ocean. It is consistently the world's most visited country.",
    known: [
      "Eiffel Tower",
      "Wine and cheese",
      "Haute cuisine",
      "Louvre and art museums",
      "Fashion houses",
      "Tour de France",
    ],
  },
  {
    code: "DE",
    name: "Germany",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["German"],
    dialCode: "+49",
    population: 84_500_000,
    area: 357_596,
    driving: "right",
    tld: ".de",
    about:
      "Central Europe's most populous country and its largest economy, organised as a federation of sixteen states. Engineering and manufacturing anchor its export trade.",
    known: [
      "Automotive engineering",
      "Oktoberfest",
      "Bread and beer traditions",
      "Autobahn",
      "Classical music",
      "Black Forest and Bavaria",
    ],
  },
  {
    code: "IT",
    name: "Italy",
    capital: "Rome",
    region: "Europe",
    subregion: "Southern Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["Italian"],
    dialCode: "+39",
    population: 58_900_000,
    area: 301_340,
    driving: "right",
    tld: ".it",
    about:
      "A Mediterranean peninsula shaped by the Roman Empire and the Renaissance, with Sicily, Sardinia and the Alps at its edges. It holds more UNESCO World Heritage sites than any other country.",
    known: [
      "Colosseum and Roman ruins",
      "Renaissance art",
      "Pasta and pizza",
      "Venice canals",
      "Fashion and design",
      "Espresso culture",
    ],
  },
  {
    code: "ES",
    name: "Spain",
    capital: "Madrid",
    region: "Europe",
    subregion: "Southern Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["Spanish", "Catalan", "Galician", "Basque"],
    dialCode: "+34",
    population: 48_400_000,
    area: 505_992,
    driving: "right",
    tld: ".es",
    about:
      "Most of the Iberian Peninsula plus the Balearic and Canary islands, with strong regional languages and identities. Moorish and Christian histories are layered across its architecture.",
    known: [
      "Flamenco",
      "Tapas and paella",
      "Sagrada Família",
      "Alhambra",
      "La Liga football",
      "Camino de Santiago",
    ],
  },
  {
    code: "PT",
    name: "Portugal",
    capital: "Lisbon",
    region: "Europe",
    subregion: "Southern Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["Portuguese"],
    dialCode: "+351",
    population: 10_600_000,
    area: 92_212,
    driving: "right",
    tld: ".pt",
    about:
      "Europe's westernmost mainland country, facing the Atlantic along the Iberian Peninsula. Its Age of Discovery voyages spread Portuguese across four continents.",
    known: [
      "Port wine",
      "Fado music",
      "Azulejo tiles",
      "Pastéis de nata",
      "Algarve coast",
      "Surfing at Nazaré",
    ],
  },
  {
    code: "NL",
    name: "Netherlands",
    capital: "Amsterdam",
    region: "Europe",
    subregion: "Western Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["Dutch"],
    dialCode: "+31",
    population: 17_900_000,
    area: 41_850,
    driving: "right",
    tld: ".nl",
    about:
      "A low-lying North Sea country where much of the land sits at or below sea level behind an engineered system of dykes and polders. Amsterdam is the capital; the government sits in The Hague.",
    known: [
      "Cycling culture",
      "Tulips and flower auctions",
      "Canals and windmills",
      "Delta works flood defences",
      "Dutch Masters painting",
      "Port of Rotterdam",
    ],
  },
  {
    code: "BE",
    name: "Belgium",
    capital: "Brussels",
    region: "Europe",
    subregion: "Western Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["Dutch", "French", "German"],
    dialCode: "+32",
    population: 11_700_000,
    area: 30_528,
    driving: "right",
    tld: ".be",
    about:
      "A trilingual federal state split between Dutch-speaking Flanders and French-speaking Wallonia. Brussels hosts the main institutions of the European Union and NATO's headquarters.",
    known: [
      "EU institutions",
      "Belgian chocolate",
      "Trappist beers",
      "Waffles and frites",
      "Comic strip tradition",
      "Medieval city centres",
    ],
  },
  {
    code: "CH",
    name: "Switzerland",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
    currency: "Swiss franc",
    currencyCode: "CHF",
    currencySymbol: "CHF",
    languages: ["German", "French", "Italian", "Romansh"],
    dialCode: "+41",
    population: 8_800_000,
    area: 41_285,
    driving: "right",
    tld: ".ch",
    about:
      "A landlocked Alpine confederation of 26 cantons with four national languages and a long-standing policy of armed neutrality. Zurich and Geneva are major financial and diplomatic centres.",
    known: [
      "Alps and skiing",
      "Watchmaking",
      "Swiss chocolate and cheese",
      "Banking and finance",
      "Neutrality",
      "CERN",
    ],
  },
  {
    code: "AT",
    name: "Austria",
    capital: "Vienna",
    region: "Europe",
    subregion: "Western Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["German"],
    dialCode: "+43",
    population: 9_100_000,
    area: 83_879,
    driving: "right",
    tld: ".at",
    about:
      "An Alpine, landlocked country at the centre of Europe, once the seat of the Habsburg empire. Vienna regularly ranks among the world's most liveable cities.",
    known: [
      "Classical music and opera",
      "Alpine skiing",
      "Vienna coffee houses",
      "Sachertorte",
      "Habsburg palaces",
      "Salzburg old town",
    ],
  },
  {
    code: "SE",
    name: "Sweden",
    capital: "Stockholm",
    region: "Europe",
    subregion: "Northern Europe",
    currency: "Swedish krona",
    currencyCode: "SEK",
    currencySymbol: "kr",
    languages: ["Swedish"],
    dialCode: "+46",
    population: 10_600_000,
    area: 450_295,
    driving: "right",
    tld: ".se",
    about:
      "The largest Nordic country, running far enough north that the sun barely sets in midsummer above the Arctic Circle. Its capital is built across fourteen islands.",
    known: [
      "Nobel Prizes",
      "IKEA and Swedish design",
      "Midnight sun and northern lights",
      "Fika coffee break",
      "Music export industry",
      "Allemansrätten (right to roam)",
    ],
  },
  {
    code: "NO",
    name: "Norway",
    capital: "Oslo",
    region: "Europe",
    subregion: "Northern Europe",
    currency: "Norwegian krone",
    currencyCode: "NOK",
    currencySymbol: "kr",
    languages: ["Norwegian"],
    dialCode: "+47",
    population: 5_500_000,
    area: 385_207,
    driving: "right",
    tld: ".no",
    about:
      "A long Scandinavian coastline cut by glacier-carved fjords, reaching well past the Arctic Circle. Offshore oil and gas fund one of the world's largest sovereign wealth funds.",
    known: [
      "Fjords",
      "Northern lights",
      "Viking heritage",
      "Sovereign wealth fund",
      "Electric-vehicle adoption",
      "Cross-country skiing",
    ],
  },
  {
    code: "DK",
    name: "Denmark",
    capital: "Copenhagen",
    region: "Europe",
    subregion: "Northern Europe",
    currency: "Danish krone",
    currencyCode: "DKK",
    currencySymbol: "kr",
    languages: ["Danish"],
    dialCode: "+45",
    population: 5_900_000,
    area: 42_933,
    driving: "right",
    tld: ".dk",
    about:
      "A flat, low-lying Nordic kingdom spread over the Jutland peninsula and some 400 islands. The Faroe Islands and Greenland are autonomous territories within the realm.",
    known: [
      "Hygge",
      "LEGO",
      "Cycling infrastructure",
      "Wind power",
      "Danish design",
      "New Nordic cuisine",
    ],
  },
  {
    code: "FI",
    name: "Finland",
    capital: "Helsinki",
    region: "Europe",
    subregion: "Northern Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["Finnish", "Swedish"],
    dialCode: "+358",
    population: 5_600_000,
    area: 338_455,
    driving: "right",
    tld: ".fi",
    about:
      "A forested Nordic country with something close to 188,000 lakes, bordering Russia along its eastern edge. Its education system and reported life satisfaction are frequently cited as world-leading.",
    known: [
      "Saunas",
      "Lakes and forests",
      "Lapland and Santa Claus Village",
      "Education system",
      "Nokia",
      "Northern lights",
    ],
  },
  {
    code: "IS",
    name: "Iceland",
    capital: "Reykjavík",
    region: "Europe",
    subregion: "Northern Europe",
    currency: "Icelandic króna",
    currencyCode: "ISK",
    currencySymbol: "kr",
    languages: ["Icelandic"],
    dialCode: "+354",
    population: 390_000,
    area: 103_000,
    driving: "right",
    tld: ".is",
    about:
      "A volcanic North Atlantic island sitting on the Mid-Atlantic Ridge, where glaciers and active volcanoes share the same landscape. Almost all its electricity and heating come from renewable sources.",
    known: [
      "Volcanoes and geysers",
      "Blue Lagoon",
      "Geothermal energy",
      "Glaciers and waterfalls",
      "Northern lights",
      "Sagas and folklore",
    ],
  },
  {
    code: "PL",
    name: "Poland",
    capital: "Warsaw",
    region: "Europe",
    subregion: "Eastern Europe",
    currency: "Polish złoty",
    currencyCode: "PLN",
    currencySymbol: "zł",
    languages: ["Polish"],
    dialCode: "+48",
    population: 36_700_000,
    area: 312_696,
    driving: "right",
    tld: ".pl",
    about:
      "A Central European country on the North European Plain, rebuilt extensively after the Second World War. Kraków's old town and the Białowieża primeval forest are among its best-known sites.",
    known: [
      "Kraków old town",
      "Pierogi",
      "Chopin",
      "Białowieża forest",
      "Amber crafts",
      "Salt mines at Wieliczka",
    ],
  },
  {
    code: "CZ",
    name: "Czechia",
    capital: "Prague",
    region: "Europe",
    subregion: "Eastern Europe",
    currency: "Czech koruna",
    currencyCode: "CZK",
    currencySymbol: "Kč",
    languages: ["Czech"],
    dialCode: "+420",
    population: 10_900_000,
    area: 78_871,
    driving: "right",
    tld: ".cz",
    about:
      "A landlocked country of Bohemia, Moravia and Czech Silesia, with a capital whose medieval core survived the twentieth century largely intact. It has the world's highest beer consumption per head.",
    known: [
      "Prague Castle and Charles Bridge",
      "Pilsner beer",
      "Bohemian crystal",
      "Spa towns",
      "Castles and chateaux",
      "Puppetry tradition",
    ],
  },
  {
    code: "HU",
    name: "Hungary",
    capital: "Budapest",
    region: "Europe",
    subregion: "Eastern Europe",
    currency: "Hungarian forint",
    currencyCode: "HUF",
    currencySymbol: "Ft",
    languages: ["Hungarian"],
    dialCode: "+36",
    population: 9_600_000,
    area: 93_028,
    driving: "right",
    tld: ".hu",
    about:
      "A landlocked country on the Carpathian Basin, split by the Danube into historic Buda and Pest. Hungarian is unrelated to the Slavic and Germanic languages around it.",
    known: [
      "Thermal baths",
      "Goulash and paprika",
      "Danube and Parliament building",
      "Tokaji wine",
      "Lake Balaton",
      "Rubik's Cube",
    ],
  },
  {
    code: "GR",
    name: "Greece",
    capital: "Athens",
    region: "Europe",
    subregion: "Southern Europe",
    currency: "Euro",
    currencyCode: "EUR",
    currencySymbol: "€",
    languages: ["Greek"],
    dialCode: "+30",
    population: 10_400_000,
    area: 131_957,
    driving: "right",
    tld: ".gr",
    about:
      "A Mediterranean country of mountainous mainland and thousands of islands, and the birthplace of Western philosophy, drama and democracy. Tourism and shipping are its largest industries.",
    known: [
      "Acropolis of Athens",
      "Santorini and the islands",
      "Ancient philosophy",
      "Olive oil and feta",
      "Birthplace of the Olympics",
      "Merchant shipping",
    ],
  },
  {
    code: "RU",
    name: "Russia",
    capital: "Moscow",
    region: "Europe",
    subregion: "Eastern Europe",
    currency: "Russian ruble",
    currencyCode: "RUB",
    currencySymbol: "₽",
    languages: ["Russian"],
    dialCode: "+7",
    population: 144_000_000,
    area: 17_098_246,
    driving: "right",
    tld: ".ru",
    about:
      "The largest country on Earth by area, spanning eleven time zones from the Baltic to the Pacific. Most of its population lives west of the Urals.",
    known: [
      "Eleven time zones",
      "Trans-Siberian Railway",
      "Red Square and the Kremlin",
      "Russian literature and ballet",
      "Lake Baikal",
      "Oil and natural gas",
    ],
  },
  {
    code: "UA",
    name: "Ukraine",
    capital: "Kyiv",
    region: "Europe",
    subregion: "Eastern Europe",
    currency: "Ukrainian hryvnia",
    currencyCode: "UAH",
    currencySymbol: "₴",
    languages: ["Ukrainian"],
    dialCode: "+380",
    population: 37_700_000,
    area: 603_500,
    driving: "right",
    tld: ".ua",
    about:
      "The largest country lying wholly within Europe, covering broad plains of exceptionally fertile black-earth soil. It is historically one of the world's major grain exporters.",
    known: [
      "Black-earth farmland",
      "Grain and sunflower oil exports",
      "Kyiv's Saint Sophia Cathedral",
      "Carpathian mountains",
      "Borscht",
      "Embroidered vyshyvanka",
    ],
  },
  {
    code: "RO",
    name: "Romania",
    capital: "Bucharest",
    region: "Europe",
    subregion: "Eastern Europe",
    currency: "Romanian leu",
    currencyCode: "RON",
    currencySymbol: "lei",
    languages: ["Romanian"],
    dialCode: "+40",
    population: 19_000_000,
    area: 238_397,
    driving: "right",
    tld: ".ro",
    about:
      "A Carpathian and Black Sea country whose language is Romance, unusually for the region. The Danube delta on its coast is Europe's best-preserved river delta.",
    known: [
      "Transylvania and Bran Castle",
      "Carpathian mountains",
      "Danube delta",
      "Painted monasteries",
      "Wooden churches of Maramureș",
      "Software industry",
    ],
  },

  /* ----------------------------- Americas ------------------------------ */
  {
    code: "US",
    name: "United States",
    capital: "Washington, D.C.",
    region: "Americas",
    subregion: "Northern America",
    currency: "US dollar",
    currencyCode: "USD",
    currencySymbol: "$",
    languages: ["English", "Spanish"],
    dialCode: "+1",
    population: 341_000_000,
    area: 9_833_517,
    driving: "right",
    tld: ".us",
    newsQuery: "hl=en-US&gl=US&ceid=US:en",
    about:
      "A federation of fifty states spanning North America, plus Alaska and Hawaii, covering six main time zones. It has the world's largest economy by nominal GDP.",
    known: [
      "Silicon Valley",
      "Hollywood",
      "National parks",
      "Jazz, blues and hip-hop",
      "Space programme",
      "Interstate road trips",
    ],
  },
  {
    code: "CA",
    name: "Canada",
    capital: "Ottawa",
    region: "Americas",
    subregion: "Northern America",
    currency: "Canadian dollar",
    currencyCode: "CAD",
    currencySymbol: "C$",
    languages: ["English", "French"],
    dialCode: "+1",
    population: 40_100_000,
    area: 9_984_670,
    driving: "right",
    tld: ".ca",
    about:
      "The second largest country by area and the one with the longest coastline, yet most of its people live within a few hundred kilometres of the US border. It is officially bilingual in English and French.",
    known: [
      "Maple syrup",
      "Ice hockey",
      "Rocky Mountains",
      "Niagara Falls",
      "Northern lights",
      "Vast lakes and forests",
    ],
  },
  {
    code: "MX",
    name: "Mexico",
    capital: "Mexico City",
    region: "Americas",
    subregion: "Central America",
    currency: "Mexican peso",
    currencyCode: "MXN",
    currencySymbol: "$",
    languages: ["Spanish"],
    dialCode: "+52",
    population: 129_000_000,
    area: 1_964_375,
    driving: "right",
    tld: ".mx",
    about:
      "The most populous Spanish-speaking country, bridging North and Central America between the Pacific and the Gulf of Mexico. Maya and Aztec civilisations left ruins across its south and centre.",
    known: [
      "Tacos and mole",
      "Day of the Dead",
      "Maya and Aztec ruins",
      "Mariachi music",
      "Tequila and mezcal",
      "Yucatán cenotes",
    ],
  },
  {
    code: "BR",
    name: "Brazil",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
    currency: "Brazilian real",
    currencyCode: "BRL",
    currencySymbol: "R$",
    languages: ["Portuguese"],
    dialCode: "+55",
    population: 217_000_000,
    area: 8_515_767,
    driving: "right",
    tld: ".br",
    about:
      "South America's largest country by area and population, holding most of the Amazon basin. It is the only Portuguese-speaking country in the Americas.",
    known: [
      "Amazon rainforest",
      "Rio Carnival",
      "Football",
      "Samba and bossa nova",
      "Coffee production",
      "Christ the Redeemer",
    ],
  },
  {
    code: "AR",
    name: "Argentina",
    capital: "Buenos Aires",
    region: "Americas",
    subregion: "South America",
    currency: "Argentine peso",
    currencyCode: "ARS",
    currencySymbol: "$",
    languages: ["Spanish"],
    dialCode: "+54",
    population: 45_700_000,
    area: 2_780_400,
    driving: "right",
    tld: ".ar",
    about:
      "Reaching from subtropical north to sub-Antarctic Tierra del Fuego, with the Andes forming its entire western border. The Pampas grasslands underpin its cattle and grain exports.",
    known: [
      "Tango",
      "Beef and asado",
      "Malbec wine",
      "Patagonia",
      "Iguazú Falls",
      "Football",
    ],
  },
  {
    code: "CL",
    name: "Chile",
    capital: "Santiago",
    region: "Americas",
    subregion: "South America",
    currency: "Chilean peso",
    currencyCode: "CLP",
    currencySymbol: "$",
    languages: ["Spanish"],
    dialCode: "+56",
    population: 19_600_000,
    area: 756_102,
    driving: "right",
    tld: ".cl",
    about:
      "A ribbon of land more than 4,000 km long and rarely more than 200 km wide, pinned between the Andes and the Pacific. It runs from the Atacama, the driest non-polar desert, to Patagonian ice fields.",
    known: [
      "Atacama Desert",
      "Copper mining",
      "Chilean wine",
      "Patagonia and Torres del Paine",
      "Easter Island",
      "Astronomical observatories",
    ],
  },
  {
    code: "CO",
    name: "Colombia",
    capital: "Bogotá",
    region: "Americas",
    subregion: "South America",
    currency: "Colombian peso",
    currencyCode: "COP",
    currencySymbol: "$",
    languages: ["Spanish"],
    dialCode: "+57",
    population: 52_300_000,
    area: 1_141_748,
    driving: "right",
    tld: ".co",
    about:
      "The only South American country with both Caribbean and Pacific coastlines, crossed by three ranges of the Andes. It is among the most biodiverse countries on Earth, especially for birds.",
    known: [
      "Coffee",
      "Emeralds",
      "Cumbia and vallenato",
      "Cartagena's walled city",
      "Bird biodiversity",
      "Gabriel García Márquez",
    ],
  },
  {
    code: "PE",
    name: "Peru",
    capital: "Lima",
    region: "Americas",
    subregion: "South America",
    currency: "Peruvian sol",
    currencyCode: "PEN",
    currencySymbol: "S/",
    languages: ["Spanish", "Quechua", "Aymara"],
    dialCode: "+51",
    population: 34_400_000,
    area: 1_285_216,
    driving: "right",
    tld: ".pe",
    about:
      "Home to the heart of the Inca empire, with a desert coast, Andean highlands and Amazon lowlands within one country. Lima's cuisine is among the most celebrated in the Americas.",
    known: [
      "Machu Picchu",
      "Inca heritage",
      "Ceviche and Peruvian cuisine",
      "Nazca Lines",
      "Lake Titicaca",
      "Alpaca wool",
    ],
  },
  {
    code: "CU",
    name: "Cuba",
    capital: "Havana",
    region: "Americas",
    subregion: "Caribbean",
    currency: "Cuban peso",
    currencyCode: "CUP",
    currencySymbol: "$",
    languages: ["Spanish"],
    dialCode: "+53",
    population: 11_000_000,
    area: 109_884,
    driving: "right",
    tld: ".cu",
    about:
      "The largest island in the Caribbean, lying between the Gulf of Mexico and the Atlantic. Havana's colonial centre and its mid-century American cars are its most recognisable images.",
    known: [
      "Cigars",
      "Classic American cars",
      "Son and salsa music",
      "Old Havana",
      "Rum",
      "Coral reefs",
    ],
  },
  {
    code: "JM",
    name: "Jamaica",
    capital: "Kingston",
    region: "Americas",
    subregion: "Caribbean",
    currency: "Jamaican dollar",
    currencyCode: "JMD",
    currencySymbol: "J$",
    languages: ["English", "Jamaican Patois"],
    dialCode: "+1-876",
    population: 2_800_000,
    area: 10_991,
    driving: "left",
    tld: ".jm",
    about:
      "A mountainous Caribbean island south of Cuba, and the birthplace of reggae. Its sprinters have dominated short-distance athletics for well over a decade.",
    known: [
      "Reggae and Bob Marley",
      "Blue Mountain coffee",
      "Sprinting",
      "Jerk cooking",
      "Dunn's River Falls",
      "Rastafari culture",
    ],
  },
  {
    code: "CR",
    name: "Costa Rica",
    capital: "San José",
    region: "Americas",
    subregion: "Central America",
    currency: "Costa Rican colón",
    currencyCode: "CRC",
    currencySymbol: "₡",
    languages: ["Spanish"],
    dialCode: "+506",
    population: 5_200_000,
    area: 51_100,
    driving: "right",
    tld: ".cr",
    about:
      "A Central American isthmus country between the Caribbean and the Pacific, holding an outsized share of the world's species. It abolished its standing army in 1948 and draws most of its electricity from renewables.",
    known: [
      "Rainforest biodiversity",
      "Ecotourism",
      "No standing army",
      "Renewable electricity",
      "Volcanoes",
      "Pura vida",
    ],
  },

  /* ------------------------------ Africa ------------------------------- */
  {
    code: "ZA",
    name: "South Africa",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    currency: "South African rand",
    currencyCode: "ZAR",
    currencySymbol: "R",
    languages: ["Zulu", "Xhosa", "Afrikaans", "English"],
    dialCode: "+27",
    population: 60_400_000,
    area: 1_221_037,
    driving: "left",
    tld: ".za",
    about:
      "A country at the southern tip of Africa with twelve official languages and three capitals — Pretoria (executive), Cape Town (legislative) and Bloemfontein (judicial). Its mineral wealth is among the world's largest.",
    known: [
      "Table Mountain",
      "Kruger safari parks",
      "Gold, platinum and diamonds",
      "Twelve official languages",
      "Wine of the Western Cape",
      "Nelson Mandela's legacy",
    ],
  },
  {
    code: "EG",
    name: "Egypt",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    currency: "Egyptian pound",
    currencyCode: "EGP",
    currencySymbol: "£",
    languages: ["Arabic"],
    dialCode: "+20",
    population: 114_000_000,
    area: 1_002_450,
    driving: "right",
    tld: ".eg",
    about:
      "A largely desert country whose population is concentrated along the Nile and its delta. The Suez Canal, cut through its territory, carries a significant share of world maritime trade.",
    known: [
      "Pyramids of Giza",
      "Suez Canal",
      "Nile river",
      "Ancient hieroglyphs",
      "Luxor and the Valley of the Kings",
      "Red Sea diving",
    ],
  },
  {
    code: "NG",
    name: "Nigeria",
    capital: "Abuja",
    region: "Africa",
    subregion: "Western Africa",
    currency: "Nigerian naira",
    currencyCode: "NGN",
    currencySymbol: "₦",
    languages: ["English", "Hausa", "Yoruba", "Igbo"],
    dialCode: "+234",
    population: 229_000_000,
    area: 923_769,
    driving: "right",
    tld: ".ng",
    about:
      "Africa's most populous country and one of its largest economies, with more than 250 ethnic groups. Lagos is among the fastest-growing megacities in the world.",
    known: [
      "Nollywood film industry",
      "Afrobeats music",
      "Oil production",
      "Lagos megacity",
      "Jollof rice",
      "Nok and Benin art",
    ],
  },
  {
    code: "KE",
    name: "Kenya",
    capital: "Nairobi",
    region: "Africa",
    subregion: "Eastern Africa",
    currency: "Kenyan shilling",
    currencyCode: "KES",
    currencySymbol: "KSh",
    languages: ["Swahili", "English"],
    dialCode: "+254",
    population: 55_100_000,
    area: 580_367,
    driving: "left",
    tld: ".ke",
    about:
      "An East African country on the equator, running from Indian Ocean coast through the Great Rift Valley to Mount Kenya. Nairobi is a major regional hub for business and conservation.",
    known: [
      "Maasai Mara safari",
      "Great Wildebeest Migration",
      "Long-distance runners",
      "Kenyan tea and coffee",
      "M-Pesa mobile money",
      "Great Rift Valley",
    ],
  },
  {
    code: "MA",
    name: "Morocco",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
    currency: "Moroccan dirham",
    currencyCode: "MAD",
    currencySymbol: "د.م.",
    languages: ["Arabic", "Berber (Tamazight)", "French"],
    dialCode: "+212",
    population: 37_800_000,
    area: 446_550,
    driving: "right",
    tld: ".ma",
    about:
      "A North African kingdom with Atlantic and Mediterranean coasts, the Atlas mountains inland and the Sahara beyond them. Its walled medinas at Fez and Marrakesh are among the largest anywhere.",
    known: [
      "Marrakesh souks",
      "Sahara desert",
      "Tagine and couscous",
      "Mint tea",
      "Atlas mountains",
      "Argan oil and leather",
    ],
  },
  {
    code: "ET",
    name: "Ethiopia",
    capital: "Addis Ababa",
    region: "Africa",
    subregion: "Eastern Africa",
    currency: "Ethiopian birr",
    currencyCode: "ETB",
    currencySymbol: "Br",
    languages: ["Amharic", "Oromo", "Tigrinya"],
    dialCode: "+251",
    population: 129_000_000,
    area: 1_104_300,
    driving: "right",
    tld: ".et",
    about:
      "A highland country in the Horn of Africa, the only one on the continent never formally colonised. It keeps its own 13-month calendar and counts hours from dawn.",
    known: [
      "Birthplace of coffee",
      "Rock-hewn churches of Lalibela",
      "Own 13-month calendar",
      "Injera and Ethiopian cuisine",
      "Simien mountains",
      "Ancient Aksum",
    ],
  },
  {
    code: "GH",
    name: "Ghana",
    capital: "Accra",
    region: "Africa",
    subregion: "Western Africa",
    currency: "Ghanaian cedi",
    currencyCode: "GHS",
    currencySymbol: "₵",
    languages: ["English", "Akan", "Ewe"],
    dialCode: "+233",
    population: 34_100_000,
    area: 238_533,
    driving: "right",
    tld: ".gh",
    about:
      "A West African country on the Gulf of Guinea, the first in sub-Saharan Africa to gain independence from colonial rule. Its coast lies close to the intersection of the equator and the prime meridian.",
    known: [
      "Cocoa production",
      "Kente cloth",
      "Gold mining",
      "Cape Coast castles",
      "Highlife and afrobeats",
      "Lake Volta",
    ],
  },
  {
    code: "TZ",
    name: "Tanzania",
    capital: "Dodoma",
    region: "Africa",
    subregion: "Eastern Africa",
    currency: "Tanzanian shilling",
    currencyCode: "TZS",
    currencySymbol: "TSh",
    languages: ["Swahili", "English"],
    dialCode: "+255",
    population: 67_000_000,
    area: 947_303,
    driving: "left",
    tld: ".tz",
    about:
      "An East African country holding Africa's highest mountain and part of its largest lake, plus the Zanzibar archipelago offshore. Dodoma is the political capital; Dar es Salaam remains the largest city.",
    known: [
      "Mount Kilimanjaro",
      "Serengeti National Park",
      "Zanzibar spice islands",
      "Ngorongoro Crater",
      "Swahili language and coast",
      "Olduvai Gorge fossils",
    ],
  },
  {
    code: "TN",
    name: "Tunisia",
    capital: "Tunis",
    region: "Africa",
    subregion: "Northern Africa",
    currency: "Tunisian dinar",
    currencyCode: "TND",
    currencySymbol: "د.ت",
    languages: ["Arabic", "French"],
    dialCode: "+216",
    population: 12_200_000,
    area: 163_610,
    driving: "right",
    tld: ".tn",
    about:
      "The northernmost country in Africa, with a Mediterranean coast, olive-growing plains and Saharan south. Ancient Carthage stood on the edge of what is now Tunis.",
    known: [
      "Ruins of Carthage",
      "Sahara film locations",
      "Olive oil",
      "Medina of Tunis",
      "Mediterranean beaches",
      "Mosaics of El Jem",
    ],
  },

  /* ------------------------------ Oceania ------------------------------ */
  {
    code: "AU",
    name: "Australia",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    currency: "Australian dollar",
    currencyCode: "AUD",
    currencySymbol: "A$",
    languages: ["English"],
    dialCode: "+61",
    population: 26_700_000,
    area: 7_692_024,
    driving: "left",
    tld: ".au",
    about:
      "A continent, a country and an island all at once, with most of its people on the eastern and southern coasts and an arid interior between them. Its wildlife evolved in near-isolation and is found nowhere else.",
    known: [
      "Great Barrier Reef",
      "Sydney Opera House",
      "Uluru",
      "Kangaroos and koalas",
      "Outback",
      "Surf beaches",
    ],
  },
  {
    code: "NZ",
    name: "New Zealand",
    capital: "Wellington",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    currency: "New Zealand dollar",
    currencyCode: "NZD",
    currencySymbol: "NZ$",
    languages: ["English", "Māori"],
    dialCode: "+64",
    population: 5_200_000,
    area: 268_021,
    driving: "left",
    tld: ".nz",
    about:
      "Two main islands in the south-west Pacific, roughly 2,000 km from any other country, with fjords, volcanoes and alpine ranges packed into a small area. It is among the first places on Earth to see each new day.",
    known: [
      "First to see the new day",
      "Māori culture",
      "Fiordland and Southern Alps",
      "All Blacks rugby",
      "Sheep farming",
      "Lord of the Rings filming",
    ],
  },
  {
    code: "FJ",
    name: "Fiji",
    capital: "Suva",
    region: "Oceania",
    subregion: "Melanesia",
    currency: "Fijian dollar",
    currencyCode: "FJD",
    currencySymbol: "FJ$",
    languages: ["English", "Fijian", "Fiji Hindi"],
    dialCode: "+679",
    population: 930_000,
    area: 18_274,
    driving: "left",
    tld: ".fj",
    about:
      "An archipelago of over 300 islands in the South Pacific, sitting close to the 180th meridian and the International Date Line. Tourism and sugar are its mainstays.",
    known: [
      "Coral reefs and diving",
      "Near the International Date Line",
      "Rugby sevens",
      "Kava ceremonies",
      "Sugar cane",
      "Volcanic islands",
    ],
  },
];

/** Countries indexed by ISO code, for O(1) lookups from a place. */
export const COUNTRY_BY_CODE: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c]),
);

/**
 * The Google News query string for a country's edition. Countries default to
 * the English-language edition for their own region, which is what makes the
 * headlines readable in this UI regardless of the local language.
 */
export function countryNewsQuery(country: Country): string {
  return country.newsQuery ?? `hl=en-US&gl=${country.code}&ceid=${country.code}:en`;
}

/**
 * Whether Google News publishes a real English edition for this country.
 *
 * This matters more than it looks. Asking for `ceid=JP:en` doesn't get Japanese
 * news in English — there is no such edition, so Google serves a generic
 * international English feed instead, and Japan's "local news" comes back
 * identical to the United States'. Countries where English is actually spoken
 * (India, Nigeria, Singapore, the UK…) do have their own English editions and
 * genuinely local headlines.
 *
 * So the language list doubles as the signal: English-speaking country → its
 * edition; everywhere else → search for the country by name in English, which
 * returns coverage that is at least unmistakably about that country.
 */
export function countryHasEnglishEdition(country: Country): boolean {
  return country.languages.includes("English");
}

/**
 * The Google News search URL for a country — English coverage about it, capped
 * to the last week so a quiet country doesn't surface month-old headlines.
 */
export function countrySearchUrl(country: Country): string {
  const term = `${country.newsSearch ?? country.name} when:7d`;
  return `https://news.google.com/rss/search?q=${encodeURIComponent(term)}&hl=en-US&gl=US&ceid=US:en`;
}

/** The Google News edition URL for a country. */
export function countryEditionUrl(country: Country): string {
  return `https://news.google.com/rss?${countryNewsQuery(country)}`;
}
